import type { ChazaCard } from "@/types/chaza"

/** Datos de demostración — reemplazar por Supabase en Fase 1 backend. */
export const mockChazaCards: ChazaCard[] = [
  {
    id: "1",
    slug: "el-rincon-del-tinto",
    name: "El Rincon del Tinto",
    description:
      "El mejor cafe de la Universidad. Tintos a $1.500 y arepas con queso que te hacen el dia. Mas de 5 años endulzando mañanas universitarias.",
    category: "Cafe y Bebidas",
    categorySlugs: ["cafe-bebidas"],
    location: "Edificio de Ingenieria, piso 1",
    buildingCode: "401",
    rating: 4.8,
    reviews: 142,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&h=700&fit=crop",
    tags: ["Cafe", "Arepas", "Economico", "Desayunos"],
    schedule: "Lun-Vie 6am-3pm",
    price: "$1.500",
    mapPosition: { x: 28, y: 48 },
    geo: { lat: 4.6372, lng: -74.0855 },
  },
  {
    id: "2",
    slug: "fotocopias-express",
    name: "Fotocopias Express",
    description:
      "Impresiones a color y B/N, anillados en 5 minutos. El salvavidas antes de entregar trabajos a ultima hora.",
    category: "Servicios",
    categorySlugs: ["servicios", "papeleria"],
    location: "Frente a Biblioteca Central",
    buildingCode: "538",
    rating: 4.5,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1583521214690-73421a1829a9?w=500&h=700&fit=crop",
    tags: ["Impresiones", "Anillados", "Urgente"],
    schedule: "Lun-Sab 7am-7pm",
    price: "$80",
    mapPosition: { x: 48, y: 42 },
    geo: { lat: 4.6381, lng: -74.0842 },
  },
  {
    id: "3",
    slug: "don-empanada",
    name: "Don Empanada",
    description:
      "Empanadas de carne, pollo y hawaiana hechas a mano. Las mas grandes del campus a solo $2.000. Ya son una tradicion!",
    category: "Comida",
    categorySlugs: ["comida"],
    location: "Plazoleta Central",
    buildingCode: "101",
    rating: 4.9,
    reviews: 231,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=700&fit=crop",
    tags: ["Empanadas", "Almuerzo", "Casero"],
    schedule: "Lun-Vie 10am-4pm",
    price: "$2.000",
    mapPosition: { x: 52, y: 58 },
    geo: { lat: 4.6378, lng: -74.0838 },
  },
  {
    id: "4",
    slug: "tech-repair-un",
    name: "Tech Repair UN",
    description:
      "Reparamos tu celular o portatil en el campus. Pantallas, baterias y software. Presupuesto gratis y garantia de 30 dias.",
    category: "Tecnologia",
    categorySlugs: ["tecnologia"],
    location: "Edificio de Ciencias, oficina 204",
    buildingCode: "452",
    rating: 4.6,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500&h=700&fit=crop",
    tags: ["Celulares", "Portatiles", "Garantia"],
    schedule: "Lun-Vie 9am-6pm",
    price: "Gratis",
    mapPosition: { x: 38, y: 52 },
    geo: { lat: 4.6375, lng: -74.0848 },
  },
  {
    id: "5",
    slug: "libreria-el-saber",
    name: "Libreria El Saber",
    description:
      "Libros nuevos y de segunda mano. Conseguimos ese texto que no encuentras en ningun lado. Tambien recibimos libros usados.",
    category: "Libros",
    categorySlugs: ["libros"],
    location: "Cerca porteria Carrera 30",
    buildingCode: "310",
    rating: 4.7,
    reviews: 108,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&h=700&fit=crop",
    tags: ["Libros", "Textos", "Usados", "Intercambio"],
    schedule: "Lun-Sab 8am-5pm",
    price: "$5.000",
    mapPosition: { x: 72, y: 38 },
    geo: { lat: 4.6388, lng: -74.0815 },
  },
  {
    id: "6",
    slug: "smoothie-lab-un",
    name: "Smoothie Lab",
    description: "Batidos de fruta fresca, bowl de avena y snacks saludables entre clases.",
    category: "Cafe y Bebidas",
    categorySlugs: ["cafe-bebidas", "comida"],
    location: "Bloque admin, primer piso",
    buildingCode: "102",
    rating: 4.6,
    reviews: 54,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&h=700&fit=crop",
    tags: ["Saludable", "Frio", "Batidos"],
    schedule: "Lun-Vie 8am-4pm",
    price: "$4.000",
    mapPosition: { x: 50, y: 55 },
    geo: { lat: 4.6376, lng: -74.084 },
  },
  {
    id: "7",
    slug: "manillas-un",
    name: "Manillas y Pulseras UN",
    description: "Manillas personalizadas, llaveros y detalles para tu facultad o grupo de amigos.",
    category: "Ropa y Accesorios",
    categorySlugs: ["ropa-accesorios", "arte-manualidades"],
    location: "Pasillo auditorio",
    buildingCode: "201",
    rating: 4.9,
    reviews: 203,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500&h=700&fit=crop",
    tags: ["Personalizado", "Regalos", "Economico"],
    schedule: "Mar-Sab 10am-5pm",
    price: "$3.000",
    mapPosition: { x: 46, y: 60 },
    geo: { lat: 4.6374, lng: -74.0835 },
  },
  {
    id: "8",
    slug: "arte-en-pausa",
    name: "Arte en Pausa",
    description: "Ilustraciones, stickers y prints de artistas estudiantes. Encargos por mensaje.",
    category: "Arte y Manualidades",
    categorySlugs: ["arte-manualidades"],
    location: "Zona artes, mesa exterior",
    buildingCode: "303",
    rating: 4.8,
    reviews: 41,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=700&fit=crop",
    tags: ["Dibujo", "Stickers", "Encargos"],
    schedule: "Lun-Mie-Vie 11am-4pm",
    price: "$8.000",
    mapPosition: { x: 34, y: 44 },
    geo: { lat: 4.6368, lng: -74.085 },
  },
  {
    id: "9",
    slug: "snack-rapido-26",
    name: "Snack Rapido 26",
    description: "Galletas caseras, chocolatinas y paquetes para el antojo de la tarde.",
    category: "Comida",
    categorySlugs: ["comida"],
    location: "Cerca Porteria Calle 26",
    buildingCode: "N24",
    rating: 4.5,
    reviews: 31,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&h=700&fit=crop",
    tags: ["Dulces", "Snacks", "Economico"],
    schedule: "Lun-Vie 1pm-6pm",
    price: "$500",
    mapPosition: { x: 58, y: 68 },
    geo: { lat: 4.6365, lng: -74.082 },
  },
  {
    id: "10",
    slug: "bici-fix-un",
    name: "Bici Fix UN",
    description: "Parcho de llantas, engrase y revision rapida para llegar a clase a tiempo.",
    category: "Transporte",
    categorySlugs: ["transporte", "servicios"],
    location: "Punto BicirrUN sector norte",
    buildingCode: "E12",
    rating: 4.7,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=500&h=700&fit=crop",
    tags: ["Bicicleta", "Rapido", "Campus"],
    schedule: "Mar-Jue 9am-5pm",
    price: "$3.500",
    mapPosition: { x: 42, y: 32 },
    geo: { lat: 4.639, lng: -74.086 },
  },
  {
    id: "11",
    slug: "lashes-campus",
    name: "Lashes Campus",
    description: "Perfilado de cejas y pestanas estudiantil. Agenda con un dia de anticipacion.",
    category: "Belleza",
    categorySlugs: ["belleza"],
    location: "Bloque bienestar",
    buildingCode: "215",
    rating: 4.8,
    reviews: 112,
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&h=700&fit=crop",
    tags: ["Cejas", "Pestanas", "Cita"],
    schedule: "Sab solo 9am-3pm",
    price: "$12.000",
    mapPosition: { x: 62, y: 48 },
    geo: { lat: 4.6382, lng: -74.082 },
  },
  {
    id: "12",
    slug: "pinta-cancha",
    name: "Pinta Cancha",
    description: "Camisetas de fulbol, muñequeras y accesorios deportivos con bordado.",
    category: "Deportes",
    categorySlugs: ["deportes", "ropa-accesorios"],
    location: "Junto al estadio",
    buildingCode: "S01",
    rating: 4.4,
    reviews: 88,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=500&h=700&fit=crop",
    tags: ["Futbol", "Bordado", "Equipos"],
    schedule: "Lun-Vie 12pm-6pm",
    price: "$15.000",
    mapPosition: { x: 48, y: 28 },
    geo: { lat: 4.6395, lng: -74.0835 },
  },
  {
    id: "13",
    slug: "vinilo-sonido",
    name: "Vinilo y Sonido",
    description: "Parlantes pequeños, adaptadores y cables. Ideal para ensayos de banda en la U.",
    category: "Musica",
    categorySlugs: ["musica", "tecnologia"],
    location: "Modulo de musica",
    buildingCode: "M10",
    rating: 4.5,
    reviews: 29,
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=500&h=700&fit=crop",
    tags: ["Audio", "Cables", "Stereo"],
    schedule: "Mie-Vie 10am-4pm",
    price: "$10.000",
    mapPosition: { x: 30, y: 56 },
    geo: { lat: 4.637, lng: -74.086 },
  },
  {
    id: "14",
    slug: "instant-photo-un",
    name: "Instant Photo UN",
    description: "Fotos tipo polaroid en eventos del consejo y clubes. Cita para sesiones al aire libre.",
    category: "Fotografia",
    categorySlugs: ["fotografia", "servicios"],
    location: "Plaza del Che",
    buildingCode: "P01",
    rating: 4.9,
    reviews: 64,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500&h=700&fit=crop",
    tags: ["Eventos", "Polaroid", "Recuerdos"],
    schedule: "Jue-Sab 11am-5pm",
    price: "$6.000",
    mapPosition: { x: 54, y: 52 },
    geo: { lat: 4.6379, lng: -74.0832 },
  },
]
